Feature/page category
woowa-techcamp-2021/deal-9 pull request #124
Opened 2021-07-21 14:17 UTC by dongqui

💄카테고리 아이콘 추가

2021-07-21 18:23 UTC, dongqui commented
branch가 합쳐져 있었네요 ㅠ-ㅠ

2021-07-21 21:51 UTC, Hyoukjoo requested changes

2021-07-21 21:51 UTC, Hyoukjoo commented on server/src/routes/products.js
> +
여기는 try, catch 로 감싸서 에러핸들링 해줘야 서버가 중단되지 않을 거 같습니다. 

`ProductController`로 분리하고 try catch로 감싼 뒤 에러 핸들링 부탁드립니다~!

2021-07-22 05:14 UTC, dongqui commented on server/src/routes/products.js
> +
수정완료했습니다!

2021-07-22 05:15 UTC, Hyoukjoo approved these changes

2021-07-22 05:15 UTC, Hyoukjoo commented
고생하셨씁니다~

2021-07-22 05:15 UTC, merged