💄 Atom > img, Molcule > CategoryListItem
woowa-techcamp-2021/deal-9 pull request #71
Opened 2021-07-15 17:00 UTC by dongqui

close #70

2021-07-15 23:27 UTC, Hyoukjoo requested changes

2021-07-15 23:27 UTC, Hyoukjoo commented on client/src/components/atoms/img/img.js
> +  $img.height = height;
return이 빠진거 아닌가요?

2021-07-16 00:22 UTC, dongqui commented on client/src/components/atoms/img/img.js
> +  $img.height = height;
아 맞네요; 이거 쓸려다가 아이콘 아톰 써서 테스트가 안됐네요 ㅠ

2021-07-16 01:49 UTC, dongqui commented on client/src/components/atoms/img/img.js
> +  $img.height = height;
수정했습니다!

2021-07-16 01:51 UTC, Hyoukjoo commented on client/src/components/molcules/addImgButton/addImgButton.js
> +  $imgBox.appendChild($imgCountText);
`$imgBox.append($imgIcon, $imgCountText)`로 할 수도 있습니다.

개인적으로는 `appendChild`보단 `append`를 추천합니다 ㅎ

2021-07-16 01:52 UTC, Hyoukjoo commented on client/src/components/atoms/img/img.js
> +export const createImgAtom = ({ src, width, height }) => {
아직 `createImgAtom`은 사용하는 곳이 없는거죠?

2021-07-16 01:53 UTC, dongqui commented on client/src/components/atoms/img/img.js
> +export const createImgAtom = ({ src, width, height }) => {
네 제품 이미지 올릴 때랑, 상세페이지에서 쓰일 거 같아요~!

2021-07-16 01:53 UTC, dongqui commented on client/src/components/molcules/addImgButton/addImgButton.js
> +  $imgBox.appendChild($imgCountText);
오 감사합니다! :)

2021-07-16 01:54 UTC, Hyoukjoo commented
리뷰완료!

2021-07-16 01:54 UTC, Hyoukjoo approved these changes

2021-07-16 01:55 UTC, merged